// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_submit from "./routes/api/submit.ts";
import * as $api_track from "./routes/api/track.ts";
import * as $index from "./routes/index.tsx";
import * as $solutions_data_platform_development from "./routes/solutions/data-platform-development.tsx";
import * as $ContactForm from "./islands/ContactForm.tsx";
import * as $Mermaid from "./islands/Mermaid.tsx";
import * as $NavDropdown from "./islands/NavDropdown.tsx";
import * as $WebAnalytics from "./islands/WebAnalytics.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/submit.ts": $api_submit,
    "./routes/api/track.ts": $api_track,
    "./routes/index.tsx": $index,
    "./routes/solutions/data-platform-development.tsx":
      $solutions_data_platform_development,
  },
  islands: {
    "./islands/ContactForm.tsx": $ContactForm,
    "./islands/Mermaid.tsx": $Mermaid,
    "./islands/NavDropdown.tsx": $NavDropdown,
    "./islands/WebAnalytics.tsx": $WebAnalytics,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
